#!/usr/bin/env python3
"""Turn validation/results/results.csv into a table, a chart and LaTeX.

The point of the batch is to replace single-run numbers with a distribution, so
this prints the distribution and nothing that hides it: N, how many succeeded,
and for each measure the median with the full observed range rather than a mean
on its own. Where a run failed, the phase it failed in is counted, because
"failed" without "where" cannot be acted on.

    ./scripts/run_native.sh python3 validation/summarize.py
    ./scripts/run_native.sh python3 validation/summarize.py --latex --chart

--latex writes a table that can be included in the report directly, so the
numbers in the text and the numbers in the CSV cannot drift apart.
"""
import argparse
import csv
import os
import statistics
import sys
from collections import Counter

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.path.join(REPO, 'validation', 'results')
DEFAULT_CSV = os.path.join(RESULTS, 'results.csv')

MEASURES = [
    ('duration_s', 'Trajanje misije', 's', 1),
    ('place_error_mm', 'Odstupanje odlaganja', 'mm', 1),
    ('tip_left_mm', 'Vrh lijevog alata od cilja', 'mm', 1),
    ('tip_right_mm', 'Vrh desnog alata od cilja', 'mm', 1),
]


def load(path):
    if not os.path.exists(path):
        print(f'No results at {path}. Run validation/run_batch.py first.', file=sys.stderr)
        return None
    with open(path) as handle:
        return list(csv.DictReader(handle))


def numbers(rows, key, only_success=True):
    out = []
    for row in rows:
        if only_success and row.get('outcome') != 'success':
            continue
        try:
            out.append(float(row[key]))
        except (KeyError, ValueError, TypeError):
            pass
    return out


def describe(values, digits):
    if not values:
        return None
    return {
        'n': len(values),
        'median': round(statistics.median(values), digits),
        'lo': round(min(values), digits),
        'hi': round(max(values), digits),
        'spread': (round(statistics.stdev(values), digits) if len(values) > 1 else None),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('csv_path', nargs='?', default=DEFAULT_CSV)
    parser.add_argument('--latex', action='store_true', help='also write results_table.tex')
    parser.add_argument('--chart', action='store_true', help='also write results.png')
    args = parser.parse_args()

    rows = load(args.csv_path)
    if rows is None:
        return 1
    total = len(rows)
    outcomes = Counter(row.get('outcome', '?') for row in rows)
    ok = outcomes.get('success', 0)

    print(f'\nRuns: {total}')
    print(f'Successful: {ok}/{total} ({100.0 * ok / total:.0f} %)' if total else 'no runs')
    print('\nIshodi:')
    for name, count in outcomes.most_common():
        print(f'  {name:<14} {count:3d}')

    failed = [r for r in rows if r.get('outcome') != 'success']
    if failed:
        print('\nGdje su neuspjesi stali:')
        for phase, count in Counter(
                (r.get('last_phase') or 'nepoznato') for r in failed).most_common():
            print(f'  {count:3d} x  {phase[:70]}')
        reasons = Counter(r['reason'] for r in failed if r.get('reason'))
        if reasons:
            print('\nRazlozi prekida:')
            for reason, count in reasons.most_common():
                print(f'  {count:3d} x  {reason[:70]}')

    print('\nMjere (samo uspješni runovi; medijan i raspon):')
    summary = []
    for key, label, unit, digits in MEASURES:
        stats = describe(numbers(rows, key), digits)
        if stats is None:
            print(f'  {label:<32} -')
            continue
        spread = f', sd {stats["spread"]}' if stats['spread'] is not None else ''
        print(f'  {label:<32} {stats["median"]} {unit}  '
              f'[{stats["lo"]} – {stats["hi"]}]{spread}   n={stats["n"]}')
        summary.append((label, unit, stats))

    if args.latex:
        path = os.path.join(RESULTS, 'results_table.tex')
        with open(path, 'w') as handle:
            handle.write('% Generated by validation/summarize.py - do not edit by hand.\n')
            handle.write('\\begin{table}[!htb]\n    \\centering\n')
            handle.write(f'    \\caption{{Rezultati {total} uzastopnih izvo\\dj{{}}enja '
                         f'cjelovite misije}}\n')
            handle.write('    \\label{tab:statistika}\n    \\scriptsize\n')
            handle.write('    \\begin{tabularx}{\\textwidth}{@{}X l l l@{}}\n        \\toprule\n')
            handle.write('        \\textbf{Mjera} & \\textbf{Medijan} & '
                         '\\textbf{Raspon} & \\textbf{$N$} \\\\\n        \\midrule\n')
            handle.write(f'        Uspje\\v{{s}}nost & {ok}/{total} & --- & {total} \\\\\n')
            for label, unit, stats in summary:
                handle.write(f'        {label} & {stats["median"]} {unit} & '
                             f'{stats["lo"]}--{stats["hi"]} {unit} & {stats["n"]} \\\\\n')
            handle.write('        \\bottomrule\n    \\end{tabularx}\n\\end{table}\n')
        print(f'\nWrote {path}')

    if args.chart:
        try:
            import matplotlib
            matplotlib.use('Agg')
            import matplotlib.pyplot as plt
        except ImportError:
            print('matplotlib is not installed; skipping the chart', file=sys.stderr)
            return 0
        errors = numbers(rows, 'place_error_mm')
        figure, axes = plt.subplots(1, 2, figsize=(9, 3.4))
        if errors:
            axes[0].hist(errors, bins=min(12, max(3, len(errors))),
                         color='#2b6cb0', edgecolor='white')
            axes[0].set_xlabel('odstupanje odlaganja [mm]')
            axes[0].set_ylabel('broj izvođenja')
        axes[0].set_title(f'Točnost odlaganja (n={len(errors)})')

        # Every run on the axis, not just the ones that worked: a duration plot
        # that silently drops the failures is the chart equivalent of quoting
        # only the good run.
        colours = {'success': '#276749'}
        for index, row in enumerate(rows, start=1):
            try:
                duration = float(row['duration_s'])
            except (KeyError, ValueError, TypeError):
                continue
            outcome = row.get('outcome', '?')
            axes[1].plot(index, duration, 'o',
                         color=colours.get(outcome, '#9b2c2c'),
                         label=('uspjeh' if outcome == 'success' else 'neuspjeh'))
        axes[1].set_xlabel('redni broj izvođenja')
        axes[1].set_ylabel('trajanje [s]')
        axes[1].set_title('Trajanje po izvođenju')
        handles, labels = axes[1].get_legend_handles_labels()
        unique = dict(zip(labels, handles))
        if unique:
            axes[1].legend(unique.values(), unique.keys(), fontsize=8)
        for axis in axes:
            axis.grid(alpha=0.3)
        figure.tight_layout()
        path = os.path.join(RESULTS, 'results.png')
        figure.savefig(path, dpi=150)
        print(f'Wrote {path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
